// Estilos compartidos para el panel admin dark
export const S = {
  page: { color: "#94a3b8" } as React.CSSProperties,

  // Cards / panels
  card: {
    background: "#1a1d27",
    border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: 12,
  } as React.CSSProperties,

  // Tabla
  thead: {
    background: "#13151c",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  } as React.CSSProperties,
  th: {
    padding: "10px 14px",
    fontSize: 11,
    fontWeight: 600,
    color: "#475569",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
  },
  tr: {
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    transition: "background 0.12s",
  },
  td: {
    padding: "11px 14px",
    fontSize: 13,
    color: "#cbd5e1",
  } as React.CSSProperties,
  tdMuted: {
    padding: "11px 14px",
    fontSize: 12,
    color: "#475569",
  } as React.CSSProperties,

  // Inputs
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    background: "#0f1117",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "#e2e8f0",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box" as const,
    transition: "border-color 0.15s",
  } as React.CSSProperties,
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 600,
    color: "#475569",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 6,
  } as React.CSSProperties,

  // Botones
  btnPrimary: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    background: "#3b82f6",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontSize: 13,
    fontWeight: 500,
    padding: "9px 16px",
    cursor: "pointer",
    transition: "background 0.15s",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  btnGhost: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 8,
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: 400,
    padding: "9px 16px",
    cursor: "pointer",
    transition: "all 0.15s",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  btnDanger: {
    background: "none",
    border: "none",
    color: "#f87171",
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
    transition: "color 0.15s",
  } as React.CSSProperties,

  // Badge
  badgeGreen: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 9px",
    borderRadius: 20,
    background: "rgba(16,185,129,0.12)",
    color: "#34d399",
    border: "1px solid rgba(16,185,129,0.2)",
  } as React.CSSProperties,
  badgeRed: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 9px",
    borderRadius: 20,
    background: "rgba(239,68,68,0.1)",
    color: "#f87171",
    border: "1px solid rgba(239,68,68,0.2)",
  } as React.CSSProperties,
  badgeBlue: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 9px",
    borderRadius: 20,
    background: "rgba(59,130,246,0.12)",
    color: "#60a5fa",
    border: "1px solid rgba(59,130,246,0.2)",
  } as React.CSSProperties,

  // Modal overlay
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 50,
  },
  modal: {
    background: "#1a1d27",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 14,
    width: "100%",
    maxWidth: 480,
  } as React.CSSProperties,
  modalHeader: {
    padding: "18px 20px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } as React.CSSProperties,
  modalBody: { padding: "20px" } as React.CSSProperties,
  modalFooter: {
    padding: "14px 20px",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    gap: 10,
  } as React.CSSProperties,
};
